DROP DATABASE IF EXISTS UsersMagazinesDB;

CREATE DATABASE UsersMagazinesDB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE UsersMagazinesDB;

CREATE TABLE Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Magazines (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    text TEXT NOT NULL
);

